#############################################################################
# Makefile for building: STM32_UART_Bootloader_Flasher
# Generated by qmake (3.1) (Qt 5.12.12)
# Project:  STM32_UART_Bootloader_Flasher.pro
# Template: subdirs
# Command: C:\Qt\Qt5.12.12\5.12.12\mingw73_64\bin\qmake.exe -o Makefile STM32_UART_Bootloader_Flasher.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = C:\Qt\Qt5.12.12\5.12.12\mingw73_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\Qt5.12.12\5.12.12\mingw73_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\Qt5.12.12\5.12.12\mingw73_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-Core-Core-pro \
		sub-CLI-CLI-pro \
		sub-GUI-GUI-pro


sub-Core-Core-pro-qmake_all:  FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd Core\ && $(MAKE) -f Makefile qmake_all
sub-Core-Core-pro: FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-Core-Core-pro-make_first-ordered: FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Core-Core-pro-make_first: FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-Core-Core-pro-all-ordered: FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Core-Core-pro-all: FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-Core-Core-pro-clean-ordered: FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Core-Core-pro-clean: FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-Core-Core-pro-distclean-ordered: FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Core-Core-pro-distclean: FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-Core-Core-pro-install_subtargets-ordered: FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Core-Core-pro-install_subtargets: FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-Core-Core-pro-uninstall_subtargets-ordered: FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-Core-Core-pro-uninstall_subtargets: FORCE
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-CLI-CLI-pro-qmake_all: sub-Core-Core-pro-qmake_all FORCE
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd CLI\ && $(MAKE) -f Makefile qmake_all
sub-CLI-CLI-pro: sub-Core-Core-pro FORCE
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-CLI-CLI-pro-make_first-ordered: sub-Core-Core-pro-make_first-ordered  FORCE
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-CLI-CLI-pro-make_first: sub-Core-Core-pro-make_first FORCE
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-CLI-CLI-pro-all-ordered: sub-Core-Core-pro-all-ordered  FORCE
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-CLI-CLI-pro-all: sub-Core-Core-pro-all FORCE
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-CLI-CLI-pro-clean-ordered: sub-Core-Core-pro-clean-ordered  FORCE
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-CLI-CLI-pro-clean: sub-Core-Core-pro-clean FORCE
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-CLI-CLI-pro-distclean-ordered: sub-Core-Core-pro-distclean-ordered  FORCE
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-CLI-CLI-pro-distclean: sub-Core-Core-pro-distclean FORCE
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-CLI-CLI-pro-install_subtargets-ordered: sub-Core-Core-pro-install_subtargets-ordered  FORCE
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-CLI-CLI-pro-install_subtargets: sub-Core-Core-pro-install_subtargets FORCE
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-CLI-CLI-pro-uninstall_subtargets-ordered: sub-Core-Core-pro-uninstall_subtargets-ordered  FORCE
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-CLI-CLI-pro-uninstall_subtargets: sub-Core-Core-pro-uninstall_subtargets FORCE
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-GUI-GUI-pro-qmake_all: sub-CLI-CLI-pro-qmake_all FORCE
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler"
	cd GUI\ && $(MAKE) -f Makefile qmake_all
sub-GUI-GUI-pro: sub-Core-Core-pro FORCE
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile
sub-GUI-GUI-pro-make_first-ordered: sub-CLI-CLI-pro-make_first-ordered  FORCE
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-GUI-GUI-pro-make_first: sub-Core-Core-pro-make_first FORCE
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile 
sub-GUI-GUI-pro-all-ordered: sub-CLI-CLI-pro-all-ordered  FORCE
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-GUI-GUI-pro-all: sub-Core-Core-pro-all FORCE
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile all
sub-GUI-GUI-pro-clean-ordered: sub-CLI-CLI-pro-clean-ordered  FORCE
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-GUI-GUI-pro-clean: sub-Core-Core-pro-clean FORCE
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile clean
sub-GUI-GUI-pro-distclean-ordered: sub-CLI-CLI-pro-distclean-ordered  FORCE
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-GUI-GUI-pro-distclean: sub-Core-Core-pro-distclean FORCE
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile distclean
sub-GUI-GUI-pro-install_subtargets-ordered: sub-CLI-CLI-pro-install_subtargets-ordered  FORCE
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-GUI-GUI-pro-install_subtargets: sub-Core-Core-pro-install_subtargets FORCE
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile install
sub-GUI-GUI-pro-uninstall_subtargets-ordered: sub-CLI-CLI-pro-uninstall_subtargets-ordered  FORCE
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall
sub-GUI-GUI-pro-uninstall_subtargets: sub-Core-Core-pro-uninstall_subtargets FORCE
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile uninstall

Makefile: STM32_UART_Bootloader_Flasher.pro C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/win32-g++/qmake.conf C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/spec_pre.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/qdevice.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/device_config.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/common/sanitize.conf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/common/gcc-base.conf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/common/g++-base.conf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/common/angle.conf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/common/windows-vulkan.conf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/common/g++-win32.conf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/qconfig.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3drender.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_axbase.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_axserver.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_dbus.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_location.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_location_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_repparser.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_script.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_script_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_scripttools.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_scxml.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_sensors.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_websockets.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_winextras.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/qt_functions.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/qt_config.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/win32-g++/qmake.conf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/exclusive_builds.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/toolchain.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/default_pre.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/win32/default_pre.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/resolve_config.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/default_post.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/resources.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/qtquickcompiler.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/precompile_header.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/warn_on.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/qmake_use.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/file_copies.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/win32/windows.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/testcase_targets.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/exceptions.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/yacc.prf \
		C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/lex.prf \
		STM32_UART_Bootloader_Flasher.pro
	$(QMAKE) -o Makefile STM32_UART_Bootloader_Flasher.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/spec_pre.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/qdevice.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/device_config.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/common/sanitize.conf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/common/gcc-base.conf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/common/g++-base.conf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/common/angle.conf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/common/windows-vulkan.conf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/common/g++-win32.conf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/qconfig.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3drender.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_axbase.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_axserver.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_core.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_core_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_dbus.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_designer.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_gui.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_help.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_help_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_location.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_location_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_network.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_network_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_nfc.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_opengl.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_positioning.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_qml.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quick.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_repparser.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_script.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_script_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_scripttools.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_scripttools_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_scxml.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_sensors.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_serialport.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_sql.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_svg.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_testlib.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_uitools.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_websockets.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_widgets.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_winextras.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_xml.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/qt_functions.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/qt_config.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/win32-g++/qmake.conf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/spec_post.prf:
.qmake.stash:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/exclusive_builds.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/toolchain.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/default_pre.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/win32/default_pre.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/resolve_config.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/exclusive_builds_post.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/default_post.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/resources.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/qtquickcompiler.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/precompile_header.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/warn_on.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/qmake_use.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/file_copies.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/win32/windows.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/testcase_targets.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/exceptions.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/yacc.prf:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/mkspecs/features/lex.prf:
STM32_UART_Bootloader_Flasher.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile STM32_UART_Bootloader_Flasher.pro -spec win32-g++ "CONFIG+=qtquickcompiler"

qmake_all: sub-Core-Core-pro-qmake_all sub-CLI-CLI-pro-qmake_all sub-GUI-GUI-pro-qmake_all FORCE

make_first: sub-Core-Core-pro-make_first-ordered sub-CLI-CLI-pro-make_first-ordered sub-GUI-GUI-pro-make_first-ordered  FORCE
all: sub-Core-Core-pro-all-ordered sub-CLI-CLI-pro-all-ordered sub-GUI-GUI-pro-all-ordered  FORCE
clean: sub-Core-Core-pro-clean-ordered sub-CLI-CLI-pro-clean-ordered sub-GUI-GUI-pro-clean-ordered  FORCE
distclean: sub-Core-Core-pro-distclean-ordered sub-CLI-CLI-pro-distclean-ordered sub-GUI-GUI-pro-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-Core-Core-pro-install_subtargets-ordered sub-CLI-CLI-pro-install_subtargets-ordered sub-GUI-GUI-pro-install_subtargets-ordered FORCE
uninstall_subtargets: sub-Core-Core-pro-uninstall_subtargets-ordered sub-CLI-CLI-pro-uninstall_subtargets-ordered sub-GUI-GUI-pro-uninstall_subtargets-ordered FORCE

sub-Core-Core-pro-debug_ordered:
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-CLI-CLI-pro-debug_ordered: sub-Core-Core-pro-debug_ordered 
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
sub-GUI-GUI-pro-debug_ordered: sub-CLI-CLI-pro-debug_ordered 
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile debug
debug: sub-Core-Core-pro-debug_ordered sub-CLI-CLI-pro-debug_ordered sub-GUI-GUI-pro-debug_ordered

sub-Core-Core-pro-release_ordered:
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-CLI-CLI-pro-release_ordered: sub-Core-Core-pro-release_ordered 
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
sub-GUI-GUI-pro-release_ordered: sub-CLI-CLI-pro-release_ordered 
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile release
release: sub-Core-Core-pro-release_ordered sub-CLI-CLI-pro-release_ordered sub-GUI-GUI-pro-release_ordered

sub-Core-Core-pro-check_ordered:
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-CLI-CLI-pro-check_ordered: sub-Core-Core-pro-check_ordered 
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
sub-GUI-GUI-pro-check_ordered: sub-CLI-CLI-pro-check_ordered 
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile check
check: sub-Core-Core-pro-check_ordered sub-CLI-CLI-pro-check_ordered sub-GUI-GUI-pro-check_ordered

sub-Core-Core-pro-benchmark_ordered:
	@if not exist Core\ mkdir Core\ & if not exist Core\ exit 1
	cd Core\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\Core\Core.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-CLI-CLI-pro-benchmark_ordered: sub-Core-Core-pro-benchmark_ordered 
	@if not exist CLI\ mkdir CLI\ & if not exist CLI\ exit 1
	cd CLI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\CLI\CLI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
sub-GUI-GUI-pro-benchmark_ordered: sub-CLI-CLI-pro-benchmark_ordered 
	@if not exist GUI\ mkdir GUI\ & if not exist GUI\ exit 1
	cd GUI\ && ( if not exist Makefile $(QMAKE) -o Makefile "C:\Users\MEHDI ASKRI\Desktop\Qt-projects\STM32_UART_Bootloader_Flasher\GUI\GUI.pro" -spec win32-g++ "CONFIG+=qtquickcompiler" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-Core-Core-pro-benchmark_ordered sub-CLI-CLI-pro-benchmark_ordered sub-GUI-GUI-pro-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

